export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const INCREMENT_ACTION_COUNT = "INCREMENT_ACTION_COUNT";
export const INCREMENT_NUMBER = "INCREMENT_NUMBER";
export const LIST_USERS = "LIST_USERS";
export const PARSE_ERROR = "PARSE_ERROR";
export const RESET_ERROR = "RESET_ERROR";
